FROM postgres:13

# Variables de entorno
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=securepassword
ENV DAYLI_BOT_USER=dayli_bot_user
ENV DAYLI_BOT_PASSWORD=securepassword
ENV DAYLI_BOT_DB=dayli_bot_db

# Copiar el script de inicialización al directorio correspondiente
COPY init-user-superuser.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init-user-superuser.sh
