# Generated by Django 5.1.1 on 2024-11-03 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='checklist',
            table='checklist',
        ),
        migrations.AlterModelTable(
            name='commitment',
            table='commitment',
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='sprint',
            table='sprint',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
        migrations.AlterModelTable(
            name='voicechannellog',
            table='voice_channel_log',
        ),
    ]
